cloud:
  aws:
    credentials:
      access-key: ##credential access-key on your aws console
      secret-key: ## credential secret-key on your aws console
    region:
      static: # region name
    stack:
      auto: false

application:
  bucket:
    name: ## bucket name which you preferred


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
